"""
agent_spec/constants.py — Shared constants across all pipeline phases.
"""

# Directories to skip when walking a repository.
# Shared by phase0_workspace, phase1_bm25, phase35_tools, embedding_indexer.
SKIP_DIRS: set = {
    # VCS / IDE
    ".git", ".svn", ".hg",
    ".idea", ".vscode",
    # Dependencies
    "node_modules", "vendor", "bower_components",
    # Python environments / caches
    ".venv", "venv", "env", "__pycache__",
    ".mypy_cache", ".pytest_cache", ".ruff_cache", ".tox",
    # Build artefacts
    "dist", "build", "target", "out", "bin", "obj",
    # Coverage / docs
    "htmlcov", "coverage", ".coverage",
    # Auto-generated code — NEVER a bug root, only noise for the ranker.
    "migrations",       # Django DB migrations (auto-generated by makemigrations)
    "__snapshots__",    # Jest / Vitest snapshot files
    "generated",        # generic generated-code folder
    "proto_gen",        # protobuf generated stubs
    "stubs",            # type stubs
}

# Source-file extensions considered by the pipeline.
SUPPORTED_EXTENSIONS: set = {
    ".py", ".js", ".ts", ".jsx", ".tsx",
    ".java", ".go", ".rs",
    ".cpp", ".cc", ".cxx", ".c", ".h", ".hpp",
    ".cs", ".rb", ".php", ".kt", ".swift",
}
